title: Art of Data
email: lester_lee@horacemann.org
description: >-
  This is the class website for Art of Data.
#Site settings
excerpt_length: 55

include: ['units']

#Build settings
markdown: kramdown
permalink: pretty
future: true
sass:
  sass_dir: css
exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'CNAME']